In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import random
%matplotlib inline

In [3]:
img_gray = cv2.imread('E:/lena.jpg', 0) # 0表示显示灰度图像
cv2.imshow('lena_grey', img_gray)
# 以下三行用于成功显示图片，esc可以直接退出显示
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [4]:
# 显示灰度图像矩阵,数值代表灰度值，明亮程度，越大表示越亮
print(img_gray)

[[131 137 131 ...  96  96  96]
 [132 135 133 ...  96  98  99]
 [134 132 135 ...  98  99 100]
 ...
 [110 109 114 ...  47  47  48]
 [107 109 111 ...  47  47  51]
 [101 107 109 ...  47  48  54]]


In [5]:
# 显示图像矩阵的数据类型，2的8次方为256,so 灰度图的值为0-255
print(img_gray.dtype)

uint8


In [6]:
# 显示图像的shape，行 * 列(像素值)
print(img_gray.shape)

(512, 512)


In [7]:
img = cv2.imread("E:/lena.jpg")
cv2.imshow("lena", img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [8]:
print(img)
print(img.shape) # 彩色图像是三个通道组合成，行*列*通道

[[[ 74 110 194]
  [ 80 116 200]
  [ 74 110 194]
  ...
  [ 55  77 148]
  [ 55  78 146]
  [ 55  78 146]]

 [[ 75 111 195]
  [ 78 114 198]
  [ 76 112 196]
  ...
  [ 55  78 146]
  [ 57  80 148]
  [ 58  81 149]]

 [[ 77 113 197]
  [ 75 111 195]
  [ 78 114 198]
  ...
  [ 55  81 148]
  [ 58  81 149]
  [ 59  83 149]]

 ...

 [[ 60  90 167]
  [ 59  89 166]
  [ 64  94 171]
  ...
  [ 38  38  68]
  [ 36  38  68]
  [ 37  39  69]]

 [[ 57  87 164]
  [ 59  89 166]
  [ 60  92 168]
  ...
  [ 38  38  68]
  [ 36  38  69]
  [ 40  42  73]]

 [[ 51  81 158]
  [ 57  87 164]
  [ 58  90 166]
  ...
  [ 38  38  68]
  [ 37  39  70]
  [ 43  45  76]]]
(512, 512, 3)


In [9]:
#color split 把三个颜色通道分开，分别显示，opencv三个通道分别为B, G, R
B, G, R = cv2.split(img)
cv2.imshow("B channel image", B)
cv2.imshow("G channel image", G)
cv2.imshow("R channel image", R)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows() # click Esc to destory all windows

In [14]:
# change color 通过随机改变各通道图像的灰度值，改变合成后图像的颜色
def random_change_color(img):
    """
    输入一副图像，输出一副颜色更改后的图像
    """
    B, G, R = cv2.split(img)
    b_rand = random.randint(-50, 50) # 生成一个随机整数，范围在-50 - 50 
    if b_rand == 0:
        pass
    elif b_rand > 0:
        lim = 255 - b_rand # 取值范围在205 - 255
        B[B > lim] = 255
        B[B <= lim] = (b_rand + B[B <= lim]).astype(img.dtype) # ?
    elif b_rand < 0:
        lim = 0 - b_rand
        B[B < lim] = 0
        B[B >= lim] = (b_rand + B[B >= lim]).astype(img.dtype)
#     return img[B]
    g_rand = random.randint(-50, 50)
    if g_rand == 0:
        pass
    elif g_rand > 0:
        lim = 255 - g_rand
        G[G > lim] = 255
        G[G <= lim] = (g_rand + G[G <= lim]).astype(img.dtype)
    elif g_rand < 0:
        lim = 0 - g_rand
        G[G < lim] = 0
        G[G >= lim] = (g_rand + G[G >= lim]).astype(img.dtype)

    r_rand = random.randint(-50, 50)
    if r_rand == 0:
        pass
    elif r_rand > 0:
        lim = 255 - r_rand
        R[R > lim] = 255
        R[R <= lim] = (r_rand + R[R <= lim]).astype(img.dtype)
    elif r_rand < 0:
        lim = 0 - r_rand
        R[R < lim] = 0
        R[R >= lim] = (r_rand + R[R >= lim]).astype(img.dtype)

    img_merge = cv2.merge((B, G, R))
    #img = cv2.cvtColor(final_hsv, cv2.COLOR_HSV2BGR)
    return img_merge

In [15]:
img_random_color = random_change_color(img)
cv2.imshow("img_random_color", img_random_color)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()